/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithUsRouteImport } from './routes/work-with-us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RealEstateVirtualAssistantRouteImport } from './routes/real-estate-virtual-assistant'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSignUpRouteImport } from './routes/courses_.sign-up'
import { Route as CoursesLoginRouteImport } from './routes/courses_.login'
import { Route as CoursesAccountRouteImport } from './routes/courses_.account'

const WorkWithUsRoute = WorkWithUsRouteImport.update({
  id: '/work-with-us',
  path: '/work-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateVirtualAssistantRoute =
  RealEstateVirtualAssistantRouteImport.update({
    id: '/real-estate-virtual-assistant',
    path: '/real-estate-virtual-assistant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSignUpRoute = CoursesSignUpRouteImport.update({
  id: '/courses_/sign-up',
  path: '/courses/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesLoginRoute = CoursesLoginRouteImport.update({
  id: '/courses_/login',
  path: '/courses/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesAccountRoute = CoursesAccountRouteImport.update({
  id: '/courses_/account',
  path: '/courses/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/real-estate-virtual-assistant': typeof RealEstateVirtualAssistantRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/courses/account': typeof CoursesAccountRoute
  '/courses/login': typeof CoursesLoginRoute
  '/courses/sign-up': typeof CoursesSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/real-estate-virtual-assistant': typeof RealEstateVirtualAssistantRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/courses/account': typeof CoursesAccountRoute
  '/courses/login': typeof CoursesLoginRoute
  '/courses/sign-up': typeof CoursesSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/real-estate-virtual-assistant': typeof RealEstateVirtualAssistantRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/work-with-us': typeof WorkWithUsRoute
  '/courses_/account': typeof CoursesAccountRoute
  '/courses_/login': typeof CoursesLoginRoute
  '/courses_/sign-up': typeof CoursesSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/privacy'
    | '/products'
    | '/real-estate-virtual-assistant'
    | '/services'
    | '/terms'
    | '/work-with-us'
    | '/courses/account'
    | '/courses/login'
    | '/courses/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/privacy'
    | '/products'
    | '/real-estate-virtual-assistant'
    | '/services'
    | '/terms'
    | '/work-with-us'
    | '/courses/account'
    | '/courses/login'
    | '/courses/sign-up'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/privacy'
    | '/products'
    | '/real-estate-virtual-assistant'
    | '/services'
    | '/terms'
    | '/work-with-us'
    | '/courses_/account'
    | '/courses_/login'
    | '/courses_/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  RealEstateVirtualAssistantRoute: typeof RealEstateVirtualAssistantRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  WorkWithUsRoute: typeof WorkWithUsRoute
  CoursesAccountRoute: typeof CoursesAccountRoute
  CoursesLoginRoute: typeof CoursesLoginRoute
  CoursesSignUpRoute: typeof CoursesSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-us': {
      id: '/work-with-us'
      path: '/work-with-us'
      fullPath: '/work-with-us'
      preLoaderRoute: typeof WorkWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate-virtual-assistant': {
      id: '/real-estate-virtual-assistant'
      path: '/real-estate-virtual-assistant'
      fullPath: '/real-estate-virtual-assistant'
      preLoaderRoute: typeof RealEstateVirtualAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/sign-up': {
      id: '/courses_/sign-up'
      path: '/courses/sign-up'
      fullPath: '/courses/sign-up'
      preLoaderRoute: typeof CoursesSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/login': {
      id: '/courses_/login'
      path: '/courses/login'
      fullPath: '/courses/login'
      preLoaderRoute: typeof CoursesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/account': {
      id: '/courses_/account'
      path: '/courses/account'
      fullPath: '/courses/account'
      preLoaderRoute: typeof CoursesAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  RealEstateVirtualAssistantRoute: RealEstateVirtualAssistantRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  WorkWithUsRoute: WorkWithUsRoute,
  CoursesAccountRoute: CoursesAccountRoute,
  CoursesLoginRoute: CoursesLoginRoute,
  CoursesSignUpRoute: CoursesSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
